---
- name: Install Postgresql
  hosts: "{{ HOSTS | default('aspect-db') }}"
  become: yes

  tasks:
  - name: Set up Postgresql repo
    shell: |
      echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    args:
      warn: no

  - name: Install Postgresql 14
    apt:
      name: postgresql-14
      update_cache: yes
      state: present

  - name: Stop & disable Postgresql service
    service: 
      name: postgresql
      state: stopped
      enabled: no

  - name: Make symlink, needed for Patroni
    shell: |
      ln -sf /usr/lib/postgresql/14/bin/* /usr/sbin/
    args:
      warn: no

  - name: Install required packages
    apt: name={{ item }} update_cache=yes state=latest
    loop: [ 'gcc', 'python3-dev', 'python3-pip', 'python3-etcd', 'libpq-dev' ]

  - name: Upgrade pip
    shell: |
      pip3 install --upgrade pip
    args:
      warn: no
      
  - name: Install from pip latest packages
    pip:     
      name: 
        - psycopg2-binary
        - patroni

  - name: Copy Patroni config
    template:
      src: "files/patroni.yml.j2"
      dest: "/etc/patroni.yml"
      owner: postgres
      group: postgres
      mode: '0644'

  - name: Create Patroni work directory
    shell: |
      mkdir -p /mnt/patroni
      chown postgres:postgres /mnt/patroni
      chmod 700 /mnt/patroni
    args:
      warn: no 

  - name: Copy patroni.service
    copy:
      src: "files/patroni.service"
      dest: "/etc/systemd/system/patroni.service"  
  - name: Reload service list
    systemd:
      daemon_reload: true
  - name: Start Patroni
    service:
      name: patroni
      state: restarted
      enabled: true

