Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.box = "centos/7"
  config.vm.network "public_network", ip: "192.168.88.25"
  config.vm.hostname = "loginom.test.local"
  config.vm.provision "shell", inline: <<-SHELL
    setenforce 0
    yum upgrade
    yum install -y curl wget mc policycoreutils-python openssh-server perl sshpass nano
    systemctl enable sshd
    systemctl start sshd
    useradd admin
    usermod -aG wheel admin
    echo 'admin ALL=(ALL) NOPASSWD:  ALL' >> /etc/sudoers
    echo "admin:yfcnhjqrf" | chpasswd
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd    
  SHELL
end
